

export const ADD_USER='ADD_USER';
export const DELETE_USER='DELETE_USER';
export const ADD_USER_SUCCESS='ADD_USER_SUCCESS';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const LOAD_USERS_SUCCESS='LOAD_USERS_SUCCESS';
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS';
export const UPDATE_USER='UPDATE_USER';

